package test;

public class MyTest {

    public static void main(String[] args) {
        System.out.println("=========== 큐 테스트 1 START ===========");
        QueueTest queueTest = new QueueTest();
        queueTest.push(11);
        queueTest.push(22);
        queueTest.front();
        queueTest.back();
        queueTest.size();
        queueTest.empty();
        queueTest.pop();
        queueTest.pop();
        queueTest.pop();
        queueTest.size();
        queueTest.empty();
        queueTest.front();
        queueTest.push(33);
        queueTest.front();
        queueTest.back();
        System.out.println("============ 큐 테스트 1 END ============");
        System.out.println("=========================================");
        System.out.println("=========================================");
        System.out.println("=========================================");
        System.out.println("=========== 큐 테스트 2 START ===========");
        QueueTest queueTest2 = new QueueTest();
        queueTest2.push(11);
        queueTest2.push(22);
        queueTest2.push(33);
        queueTest2.push(44);
        queueTest2.push(55);
        queueTest2.size();
        queueTest2.push(99999);
        queueTest2.pop();
        queueTest2.pop();
        queueTest2.push(66);
        queueTest2.size();
        queueTest2.pop();
        queueTest2.pop();
        queueTest2.pop();
        queueTest2.pop();
        queueTest2.size();
        queueTest2.pop();
        System.out.println("============ 큐 테스트 2 END ============");
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("========== 스택 테스트 1 START ==========");
        StackTest stackTest = new StackTest();
        stackTest.push(11);
        stackTest.push(22);
        stackTest.top();
        stackTest.size();
        stackTest.empty();
        stackTest.pop();
        stackTest.pop();
        stackTest.pop();
        stackTest.size();
        stackTest.empty();
        stackTest.top();
        stackTest.push(33);
        stackTest.top();
        System.out.println("=========== 스택 테스트 1 END ===========");
        System.out.println("=========================================");
        System.out.println("=========================================");
        System.out.println("=========================================");
        System.out.println("========== 스택 테스트 2 START ==========");
        StackTest stackTest2 = new StackTest();
        stackTest2.push(11);
        stackTest2.push(22);
        stackTest2.push(33);
        stackTest2.push(44);
        stackTest2.push(55);
        stackTest2.size();
        stackTest2.push(99999);
        stackTest2.pop();
        stackTest2.pop();
        stackTest2.push(66);
        stackTest2.size();
        stackTest2.pop();
        stackTest2.pop();
        stackTest2.pop();
        stackTest2.pop();
        stackTest2.size();
        stackTest2.pop();
        System.out.println("=========== 스택 테스트 2 END ===========");
    }
}
